laika.title = Explanations

laika.navigationOrder = [
  how-otel4s-context-propagation-works.md
  choosing-parent-spans-and-tracing-scopes.md
  tracing-resource-and-fs2-stream-scopes.md
  histogram-bucket-customization-with-views.md
  how-otel4s-context-works-with-the-otel4s-java-agent.md
]
