/*
 * Copyright 2023 Typelevel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.typelevel.otel4s
package semconv
package experimental.attributes

// DO NOT EDIT, this is an Auto-generated file from buildscripts/templates/registry/otel4s/attributes/SemanticAttributes.scala.j2
object PprofExperimentalAttributes {

  /** Provides an indication that multiple symbols map to this location's address, for example due to identical code
    * folding by the linker. In that case the line information represents one of the multiple symbols. This field must
    * be recomputed when the symbolization state of the profile changes.
    */
  val PprofLocationIsFolded: AttributeKey[Boolean] =
    AttributeKey("pprof.location.is_folded")

  /** Indicates that there are filenames related to this mapping.
    */
  val PprofMappingHasFilenames: AttributeKey[Boolean] =
    AttributeKey("pprof.mapping.has_filenames")

  /** Indicates that there are functions related to this mapping.
    */
  val PprofMappingHasFunctions: AttributeKey[Boolean] =
    AttributeKey("pprof.mapping.has_functions")

  /** Indicates that there are inline frames related to this mapping.
    */
  val PprofMappingHasInlineFrames: AttributeKey[Boolean] =
    AttributeKey("pprof.mapping.has_inline_frames")

  /** Indicates that there are line numbers related to this mapping.
    */
  val PprofMappingHasLineNumbers: AttributeKey[Boolean] =
    AttributeKey("pprof.mapping.has_line_numbers")

  /** Free-form text associated with the profile. This field should not be used to store any machine-readable
    * information, it is only for human-friendly content.
    */
  val PprofProfileComment: AttributeKey[Seq[String]] =
    AttributeKey("pprof.profile.comment")

  /** Documentation link for this profile type.
    *
    * @note
    *   <p> The URL must be absolute and may be missing if the profile was generated by code that did not supply a link
    */
  val PprofProfileDocUrl: AttributeKey[String] =
    AttributeKey("pprof.profile.doc_url")

  /** Frames with Function.function_name fully matching the regexp will be dropped from the samples, along with their
    * successors.
    */
  val PprofProfileDropFrames: AttributeKey[String] =
    AttributeKey("pprof.profile.drop_frames")

  /** Frames with Function.function_name fully matching the regexp will be kept, even if it matches drop_frames.
    */
  val PprofProfileKeepFrames: AttributeKey[String] =
    AttributeKey("pprof.profile.keep_frames")

  /** Records the pprof's default_sample_type in the original profile. Not set if the default sample type was missing.
    *
    * @note
    *   <p> This attribute, if present, MUST be set at the scope level
    *   (resource_profiles[].scope_profiles[].scope.attributes[]).
    */
  val PprofScopeDefaultSampleType: AttributeKey[String] =
    AttributeKey("pprof.scope.default_sample_type")

  /** Records the indexes of the sample types in the original profile.
    *
    * @note
    *   <p> This attribute, if present, MUST be set at the scope level
    *   (resource_profiles[].scope_profiles[].scope.attributes[]).
    */
  val PprofScopeSampleTypeOrder: AttributeKey[Seq[Long]] =
    AttributeKey("pprof.scope.sample_type_order")

}
