laika.title = otel4s

laika.navigationOrder = [
  index.md
  modules-structure.md
  tracing-context-propagation.md
  ecosystem.md
  how-to-jvm-setup
  how-to-tracing
  how-to-metrics
  instrumentation
  customization
  oteljava
  sdk
  examples
]
