laika.title = otel4s

laika.navigationOrder = [
  index.md
  modules-structure.md
  ecosystem.md
  how-to-jvm-setup
  how-to-tracing
  how-to-metrics
  explanations
  instrumentation
  oteljava
  sdk
  examples
]
