laika.title = How-to | JVM setup

laika.navigationOrder = [
  index.md
  set-up-otel4s-in-a-jvm-application.md
  use-the-global-opentelemetry-instance.md
  keep-otel4s-context-in-sync-with-opentelemetry-java.md
  use-the-otel4s-java-agent.md
]
