laika.title = How-to | Tracing

laika.navigationOrder = [
  index.md
  create-spans-around-effectful-code.md
  trace-resource-and-fs2-stream-code.md
  propagate-trace-context-across-service-boundaries.md
  use-otel4s-with-java-instrumented-libraries.md
]
